language: node_js
node_js: node
before_install: npm install -g grunt-cli && npm install -g bower
install: npm install && bower install
before_script: grunt publish_beta
branches:
  only:
  - dev
env:
  matrix:
    secure: Tw9upIdgIvv6KI4tz4ys80kowKL9MPxUtjMSA5nUNXEKLaDJVpJaT/ijeSPzCnrjg6Uco38eakpKdminfwAOYRwqstRmgJrfjrNcwAxZwzAOyVlyOqOPKYKJT4meshX2f6pK5odQH5yXTDxDscMgFB7GeJb0pf/VKy1pR/uSC+vjLD4M845j3ZGGOtp0tAYdGWzcg/omEaMxoNmIcG3Wo6VcenswVNzvO4Kd9p5d1HTk1fGXpR4QNcas6gwWpUTDH49x/v+nTe7W00c1Cgab4kxLvMINJwvnAhh5/cWoIbbBY75+1FGPb4kkdR6AZ8l8m0ytCn5JVnWRpay6f5TyCiD/ENxyLuIUQR53r+7ji048N5K93W4AobpAWb6vHzyEnIRc9fgYeO8wAGHUL/QVNBYntJgZlTJGXQRxfpP5BIp6cscvG4GLpNnAWd69xziRM2b4xwYkEQeTC/NfLLrgjsvfVHrUg2nP26Ilteq+qL8AVknYBJnC2xMb3/NIbAUpvahmbJpeARg7QziQSAvQ6578BUcEuxV+wCC5KPUDZz7UDivM6aZHKs1phUq2XKYj7NHq2nhtcdfkxx2edMqWyoSCCFRSgP3aG76dTT7rFB1/IjJuskOiD5AElFW2+qNiVQ6g5bj5AMgvDbBJ+l4b5G0JGVwm/y9o67g6fl712fY=
