version: "3.7"
services:
  webpack:
    container_name: dim-webpack
    image: node:10.9.0
    build:
      context: ./docker-compose/webpack
    command: bash -c "yarn install && yarn start"
    restart: always
    volumes:
      - .:/usr/src/app
  http-server:
    container_name: dim-http-server
    image: node:10.9.0
    build:
      context: ./docker-compose/http-server
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - .:/usr/src/app